#!/usr/bin/env bash

# If uninstalling, then stop nc-zabbix-agent, else do nothing
if [ "$1" = "0" ] || [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
    echo "Removing nc-zabbix-scripts..."
    if [ -d /run/systemd/system ]; then
        systemctl stop nc-zabbix-agent > /dev/null 2>&1 || :
    else
        service nc-zabbix-agent stop > /dev/null 2>&1 || :
    fi
else
    echo "Updating nc-zabbix-scripts..."
fi
